### ISSUE TITLE
Fix players being able to remove timestamps from Wheat by crafting Haybales and then crafting Wheat from the Haybales.

### ISSUE THREAD

**Issue by dmccoystephenson** [dmccoystephenson/FoodSpoilage#153]

**Comment by philbgarner** [comment]
Can you assign this one and the melon issue (#154) to me @dmccoystephenson ?  I'd like to knock out a few of these bugs this weekend.

**Comment by dmccoystephenson** [comment]
@philbgarner
Yeah I can assign those to you :) It looks like you still have a pending invitation to this repository by the way. Once you accept that I can ensure that you have the proper permissions to edit this repository.
